<article id="main">
        <h2>Naxos Online Estate Agency</h2>
        <h3>Overview</h3>
		<p>Sun, Sea, Beach, Nature, Wildlife, Culture, History, Art, Liveliness, Peace and Quiet and Outdoor Adventure - Naxos has it all. Whatever your lifestyle is, Naxos Online Estate Agency will find a community and property to match. And maybe introduce you to some areas you've never considered or even knew existed! ­­Of course, we'll help you determine how much you can spend on your Naxos property and even point you in the right direction for the best mortgage loan available in Greece, but we don't stop there. Want only a short walk to the beach? Need easy access to hiking and biking trails? Are you more oriented on living inside or outside village? Want to live on the slope of a mountain? Maybe your perfect property is already on the market. Browse through our exclusive estate agency listings for photos and detailed information about each special property and plots of land.­­</p>
        <h3>Buying a property</h3>
		<p>There are quite a number of existing properties on the market of Naxos and many of those are habitable houses which need little renovation. They are often traditionally built with use of stone and wood. There are also those existing houses which are often much older and deserted and a number of those are located in the more remote areas. These older houses require extensive renovation to make them suitable for today’s living standards and are not immediately habitable. Many people are attracted to the simplicity of traditional stone houses, however it is good to keep in mind that the renovation costs can easily exceed the cost of building a new house of similar size.</p>
		<h3>Buying a plot of land and building your own house</h3>
		<p>This option is what most people dream about when they are exploring the possibilities of buying or investing in Naxos. Building your own property on a private plot of land is a reasonable option when you have the finances to support this. When you purchase a plot of land and commission an architect you will have a lot more control over the location, views, and the proximity of neighbours.</p>
    </article>
